type StoryElement = {
  text: string;
  category: string;
  position: { x: number; y: number };
  style: {
    background: string;
    color: string;
    width: number;
    height: number;
    edgeColor: string;
  };
  options: string[];
  correctAnswer: string;
};

type StoryConnection = {
  from: number;
  to: number;
  relationship: string;
  color: string;
};

export type HistoricalEvent = {
  title: string;
  date: string;
  location: string;
  outcome: string;
  storyElements: StoryElement[];
  storyConnections: StoryConnection[];
  tags: string[];
  actors: string[];
  locations: string[];
  related_places: { type: string; name: string }[];
  dateOptions: string[];
  locationOptions: string[];
  outcomeOptions: string[];
};


export const events: HistoricalEvent[]  = [
  // Event 1: Cross-Border Attacks from Gaza
  {
    title: "Qadri Tuqan Publishes 'Ba'd al-Nakba' (After the Nakba)",
    date: "January 1950",
    location: "Beirut, Lebanon",
    outcome: "Influential work of self-criticism calling for scientific and educational reform in the Arab world.",
    storyElements: [
      {
        text: "In the wake of the 1948 'Nakba' (Catastrophe), Arab intellectuals began to analyze the causes of the defeat.",
        category: "context",
        position: { x: 100, y: 200 },
        style: {
          background: "linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)",
          color: "#333",
          width: 250,
          height: 90,
          edgeColor: "#c3cfe2",
        },
        options: [
          "Arab intellectuals began to analyze the causes of the defeat.",
          "A military coalition was formed to retake territory.",
          "Most refugees were able to return to their homes.",
          "International aid successfully rebuilt the region.",
        ],
         correctAnswer: "Arab intellectuals began to analyze the causes of the defeat.",
      },
      {
        text: "Prominent Palestinian intellectual Qadri Tuqan publishes his book 'Ba'd al-Nakba' in Beirut. [1]",
        category: "action",
        position: { x: 400, y: 100 },
        style: {
          background: "linear-gradient(135deg, #a1c4fd 0%, #c2e9fb 100%)",
          color: "#333",
          width: 260,
          height: 90,
          edgeColor: "#a1c4fd",
        },
        options: [
          "Qadri Tuqan publishes his book 'Ba'd al-Nakba'. [1]",
          "Constantine Zurayk publishes 'Ma'na al-Nakba'. [3]",
          "Musa Alami founds the Arab Development Society.",
          "Ghassan Kanafani writes 'Men in the Sun'.",
        ],
        correctAnswer: "Qadri Tuqan publishes his book 'Ba'd al-Nakba'. [1]",
      },
      {
        text: "Tuqan's book argues that the defeat was an inevitable result of Arabs ignoring science and rational methods. [2]",
        category: "thesis",
        position: { x: 700, y: 200 },
        style: {
          background: "linear-gradient(135deg, #d299c2 0%, #fef9d7 100%)",
          color: "#333",
          width: 250,
          height: 90,
          edgeColor: "#d299c2",
        },
        options: [
          "The defeat was caused by overwhelming foreign intervention.",
          "The defeat resulted from ignoring science and rational methods. [2]",
          "The defeat was due to a lack of religious faith.",
          "The defeat resulted from poor military leadership alone.",
        ],
        correctAnswer: "The defeat resulted from ignoring science and rational methods. [2]",
      },
      {
        text: "He stresses that the only way to overcome the Nakba is through acquiring scientific knowledge and combating ignorance. [2]",
        category: "solution",
        position: { x: 400, y: 350 },
        style: {
          background: "linear-gradient(135deg, #89f7fe 0%, #66a6ff 100%)",
          color: "#333",
          width: 260,
          height: 90,
          edgeColor: "#66a6ff",
        },
        options: [
          "The solution is to appeal for a UN-mandated state.",
          "The solution is an immediate military counter-attack.",
          "The solution is acquiring scientific knowledge and combating ignorance. [2]",
          "The solution is to focus solely on preserving cultural traditions.",
        ],
        correctAnswer: "The solution is acquiring scientific knowledge and combating ignorance. [2]",
      },
    ],
    storyConnections: [
      { from: 0, to: 1, relationship: "prompts", color: "#c3cfe2" },
      { from: 1, to: 2, relationship: "argues", color: "#a1c4fd" },
      { from: 2, to: 3, relationship: "therefore proposes", color: "#d299c2" },
    ],
    tags: ["Cultural", "Policy-Program"],
    actors: ["Palestine Non-Governmental"],
    locations: ["Lebanon"],
    related_places: [],
    dateOptions: [ "January 1950", "August 1948", "May 1949", "June 1951" ],
    locationOptions: [ "Beirut, Lebanon", "Amman, Jordan", "Cairo, Egypt", "Damascus, Syria" ],
    outcomeOptions: [ "A call for scientific and educational reform in the Arab world. [2]", "The formation of a new Palestinian political party.", "An agreement to publish the book in multiple languages.", "Immediate funding for new scientific universities." ],
  },
  {
    title: "Dissolution of the Jordanian Parliament",
    date: "1 January 1950",
    location: "Jordan, West Bank",
    outcome: "New elections scheduled to formally include the West Bank.",
    storyElements: [
      {
        text: "Jordan aims to hold new elections to include parliamentary deputies from the recently-annexed West Bank.",
        category: "goal",
        position: { x: 150, y: 150 },
        style: { background: "linear-gradient(135deg, #a1c4fd 0%, #c2e9fb 100%)", color: "#333", width: 260, height: 90, edgeColor: "#a1c4fd" },
        options: [ "Jordan aims to hold elections to include West Bank deputies.", "Jordan decides to postpone elections in the West Bank.", "Jordan plans to reduce the number of parliamentary seats.", "The UN calls for internationally-supervised elections in Jordan." ],
        correctAnswer: "Jordan aims to hold elections to include West Bank deputies.",
      },
      {
        text: "To enable these new elections, King Abdullah dissolves the current Jordanian parliament.",
        category: "action",
        position: { x: 500, y: 150 },
        style: { background: "linear-gradient(135deg, #ff9a9e 0%, #fad0c4 100%)", color: "#333", width: 250, height: 90, edgeColor: "#ff9a9e" },
        options: [ "King Abdullah dissolves the current Jordanian parliament.", "The Jordanian parliament votes to dissolve itself.", "King Abdullah suspends the constitution by royal decree.", "The Prime Minister and his cabinet resign." ],
        correctAnswer: "King Abdullah dissolves the current Jordanian parliament.",
      },
      {
        text: "New parliamentary elections are officially scheduled to be held on 11 April 1950.",
        category: "consequence",
        position: { x: 325, y: 350 },
        style: { background: "linear-gradient(135deg, #d299c2 0%, #fef9d7 100%)", color: "#333", width: 250, height: 80, edgeColor: "#d299c2" },
        options: [ "New parliamentary elections are scheduled for 11 April 1950.", "A constitutional referendum is scheduled for 11 April 1950.", "Martial law is declared until new elections can be held.", "The election date is postponed indefinitely." ],
        correctAnswer: "New parliamentary elections are scheduled for 11 April 1950.",
      },
    ],
    storyConnections: [
      { from: 0, to: 1, relationship: "motivates", color: "#a1c4fd" },
      { from: 1, to: 2, relationship: "leads to", color: "#ff9a9e" },
    ],
    tags: ["Institutional", "Politics"],
    actors: ["Jordan Governmental"],
    locations: ["Jordan", "West Bank"],
    related_places: [],
    dateOptions: [ "1 January 1950", "11 April 1950", "24 April 1950", "1 December 1949" ],
    locationOptions: [ "Jordan, West Bank", "Amman, Jordan", "Jerusalem", "Jordan, Syria" ],
    outcomeOptions: [ "New elections scheduled to formally include the West Bank.", "The parliament was suspended for a year.", "The West Bank was given a separate legislative council.", "King Abdullah assumed direct legislative authority." ],
  },
  {
    title: "Cross-Border Attacks from Gaza",
    date: "1950-1956",
    location: "Gaza Strip, Israel",
    outcome: "Cycle of attacks and Israeli reprisals leading to the 1956 Suez Crisis",
    storyElements: [
        {
            text: "Palestinian refugees, displaced by the 1948 war, begin infiltrating Israel for economic reasons and to retrieve property.",
            category: "trigger",
            position: { x: 100, y: 150 },
            style: { background: "linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)", color: "#333", width: 250, height: 90, edgeColor: "#c3cfe2" },
            options: ["Palestinian refugees begin infiltrating Israel for economic reasons.", "Palestinian refugees start crossing into Israel to access their former lands.", "Displaced Palestinians cross the border to retrieve property.", "Palestinians begin cross-border movements for economic survival."],
            correctAnswer: "Palestinian refugees begin infiltrating Israel for economic reasons.",
        },
        {
            text: "Egypt, controlling Gaza, begins to sponsor and train armed Fedayeen units from groups like the Muslim Brotherhood.",
            category: "organization",
            position: { x: 400, y: 100 },
            style: { background: "linear-gradient(135deg, #ff9a9e 0%, #fad0c4 100%)", color: "#333", width: 260, height: 90, edgeColor: "#ff9a9e" },
            options: ["Egypt sponsors and trains armed Fedayeen units.", "The Egyptian government starts supporting militant groups in Gaza.", "Fedayeen groups receive training and backing from Egypt.", "Egypt organizes armed Palestinian units for cross-border operations."],
            correctAnswer: "Egypt sponsors and trains armed Fedayeen units.",
        },
        {
            text: "Fedayeen launch cross-border attacks from Gaza into Israel, targeting civilians and infrastructure.",
            category: "action",
            position: { x: 700, y: 150 },
            style: { background: "linear-gradient(135deg, #89f7fe 0%, #66a6ff 100%)", color: "#333", width: 250, height: 80, edgeColor: "#66a6ff" },
            options: ["Fedayeen launch cross-border attacks from Gaza.", "Militants conduct raids from Gaza into Israeli territory.", "Armed groups initiate attacks on Israel from the Gaza Strip.", "Fedayeen carry out cross-border assaults on Israeli targets."],
            correctAnswer: "Fedayeen launch cross-border attacks from Gaza.",
        },
        {
            text: "Israel responds with large-scale military reprisal operations against targets in Gaza and the West Bank.",
            category: "response",
            position: { x: 550, y: 350 },
            style: { background: "linear-gradient(135deg, #d299c2 0%, #fef9d7 100%)", color: "#333", width: 240, height: 80, edgeColor: "#d299c2" },
            options: ["Israel responds with military reprisal operations.", "The Israeli army carries out retaliatory raids.", "Israel launches counter-attacks in response to the raids.", "Military reprisals are conducted by Israeli forces."],
            correctAnswer: "Israel responds with military reprisal operations.",
        },
        {
            text: "The cycle of Fedayeen raids and Israeli reprisals escalates tensions, contributing to the 1956 Suez Crisis.",
            category: "consequence",
            position: { x: 250, y: 380 },
            style: { background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)", color: "white", width: 260, height: 90, edgeColor: "#667eea" },
            options: ["The cycle of violence contributes to the 1956 Suez Crisis.", "Escalating attacks and reprisals lead to the Suez War.", "The ongoing conflict culminates in the 1956 Suez Crisis.", "The tensions result in the outbreak of the Suez Crisis."],
            correctAnswer: "The cycle of violence contributes to the 1956 Suez Crisis.",
        },
    ],
    storyConnections: [
      { from: 0, to: 1, relationship: "evolves into", color: "#c3cfe2" },
      { from: 1, to: 2, relationship: "enables", color: "#ff9a9e" },
      { from: 2, to: 3, relationship: "triggers", color: "#66a6ff" },
      { from: 3, to: 4, relationship: "escalates into", color: "#d299c2" },
      { from: 0, to: 4, relationship: "ultimately causes", color: "#667eea" },
    ],
    tags: ["Violence", "State Actor", "Non-State Actor"],
    actors: ["Egypt Non-Governmental", "Palestine Non-Governmental", "Israel Governmental"],
    locations: ["Gaza Strip", "Israel"],
    related_places: [],
    dateOptions: ["1950-1956", "1948-1950", "1956-1960", "1967-1970"],
    locationOptions: ["Gaza Strip, Israel", "West Bank, Jordan", "Sinai Peninsula, Egypt", "Golan Heights, Syria"],
    outcomeOptions: ["Cycle of attacks and Israeli reprisals leading to the 1956 Suez Crisis.", "A lasting ceasefire agreement was signed.", "The United Nations established a permanent peacekeeping force.", "The attacks ceased without a clear resolution."],
  },
  {
    title: "Cross-Border Attacks from Gaza",
    date: "1950",
    location: "Gaza Strip, Israel",
    outcome: "A cycle of cross-border attacks and Israeli reprisals begins.",
    storyElements: [
        {
            text: "Armed fedayeen launch cross-border attacks from Gaza into Israel.",
            category: "action",
            position: { x: 400, y: 300 },
            style: { background: "linear-gradient(135deg, #ff9a9e 0%, #fad0c4 100%)", color: "#333", width: 250, height: 90, edgeColor: "#ff9a9e" },
            options: [ "Armed fedayeen launch cross-border attacks from Gaza into Israel.", "Militant groups carry out raids from the Gaza Strip into Israeli territory.", "Palestinian fighters initiate assaults from Gaza across the armistice line.", "Armed units based in Gaza conduct attacks inside Israel's borders." ],
            correctAnswer: "Armed fedayeen launch cross-border attacks from Gaza into Israel.",
        },
        {
            text: "The attacks are organized by units of the Muslim Brotherhood and Communists.",
            category: "organization",
            position: { x: 150, y: 150 },
            style: { background: "linear-gradient(135deg, #a1c4fd 0%, #c2e9fb 100%)", color: "#333", width: 260, height: 90, edgeColor: "#a1c4fd" },
            options: [ "The attacks are organized by units of the Muslim Brotherhood and Communists.", "Units of the Muslim Brotherhood and Communists plan the cross-border raids.", "The raids are orchestrated by Muslim Brotherhood and Communist groups.", "Communist and Muslim Brotherhood units are behind the organization of the attacks." ],
            correctAnswer: "The attacks are organized by units of the Muslim Brotherhood and Communists.",
        },
        {
            text: "The attacks are a response to prior Israeli actions.",
            category: "trigger",
            position: { x: 650, y: 150 },
            style: { background: "linear-gradient(135deg, #d299c2 0%, #fef9d7 100%)", color: "#333", width: 240, height: 80, edgeColor: "#d299c2" },
            options: [ "The attacks are a response to prior Israeli actions.", "The raids come as a reaction to actions taken by Israel.", "The fedayeen attacks are initiated in response to actions by Israel.", "Israeli actions are the trigger for the cross-border attacks from Gaza." ],
            correctAnswer: "The attacks are a response to prior Israeli actions.",
        },
    ],
    storyConnections: [
      { from: 2, to: 0, relationship: "triggers", color: "#d299c2" },
      { from: 1, to: 0, relationship: "enables", color: "#a1c4fd" },
    ],
    tags: ["Violence"],
    actors: ["Egypt Non-Governmental", "Palestine Non-Governmental", "Israel Governmental"],
    locations: ["Gaza Strip", "Israel"],
    related_places: [],
    dateOptions: [ "1950", "1948", "1956", "1949" ],
    locationOptions: [ "Gaza Strip, Israel", "West Bank, Jordan", "Sinai, Egypt", "Lebanon" ],
    outcomeOptions: [ "A cycle of cross-border attacks and Israeli reprisals begins.", "A lasting ceasefire is immediately signed by both sides.", "The border between Gaza and Israel is permanently closed.", "The United Nations intervenes and creates a buffer zone." ],
  },
  {
    title: "Israel's Measures to Make Jerusalem Its Capital",
    date: "23 January 1950 - 13 July 1953",
    location: "Jerusalem",
    outcome: "Israel establishes Jerusalem as its capital by moving its government institutions there.",
    storyElements: [
        {
            text: "The Knesset proclaims that 'Jerusalem has returned to be its capital.'",
            category: "proclamation",
            position: { x: 400, y: 300 },
            style: { background: "linear-gradient(135deg, #a1c4fd 0%, #c2e9fb 100%)", color: "#333", width: 260, height: 90, edgeColor: "#a1c4fd" },
            options: [ "The Knesset proclaims that 'Jerusalem has returned to be its capital.'", "A proclamation is issued by the Knesset declaring Jerusalem as the capital.", "Israel's parliament announces that Jerusalem is once again the capital city.", "The Knesset makes a formal statement about Jerusalem's status as the capital." ],
            correctAnswer: "The Knesset proclaims that 'Jerusalem has returned to be its capital.'",
        },
        {
            text: "This was a response to a UN resolution confirming an international regime for the city.",
            category: "trigger",
            position: { x: 100, y: 150 },
            style: { background: "linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)", color: "#333", width: 250, height: 100, edgeColor: "#c3cfe2" },
            options: [ "This was a response to a UN resolution confirming an international regime for the city.", "It was a reaction to a UN resolution that affirmed an international status for Jerusalem.", "The move responded to a UN decision to make Jerusalem an international city.", "It came after the UN passed a resolution for an international administration of the city." ],
            correctAnswer: "This was a response to a UN resolution confirming an international regime for the city.",
        },
        {
            text: "Most government ministries are transferred to Jerusalem by the end of 1951.",
            category: "action",
            position: { x: 700, y: 150 },
            style: { background: "linear-gradient(135deg, #d299c2 0%, #fef9d7 100%)", color: "#333", width: 250, height: 90, edgeColor: "#d299c2" },
            options: [ "Most government ministries are transferred to Jerusalem by the end of 1951.", "By the end of 1951, the majority of government offices had been moved to Jerusalem.", "The transfer of most ministries to Jerusalem was completed by the end of 1951.", "Government offices were largely relocated to Jerusalem by the close of 1951." ],
            correctAnswer: "Most government ministries are transferred to Jerusalem by the end of 1951.",
        },
        {
            text: "The Ministry of Foreign Affairs is the last to move, on 13 July 1953.",
            category: "exception",
            position: { x: 650, y: 450 },
            style: { background: "linear-gradient(135deg, #ff9a9e 0%, #fad0c4 100%)", color: "#333", width: 240, height: 90, edgeColor: "#ff9a9e" },
            options: [ "The Ministry of Foreign Affairs is the last to move, on 13 July 1953.", "The final ministry to relocate, the Foreign Ministry, did so on 13 July 1953.", "On 13 July 1953, the transfer of the Foreign Affairs Ministry was completed.", "The move of the Foreign Ministry occurred last, on 13 July 1953." ],
            correctAnswer: "The Ministry of Foreign Affairs is the last to move, on 13 July 1953.",
        },
        {
            text: "The Ministry of Defense remains in Tel Aviv for security reasons.",
            category: "exception",
            position: { x: 150, y: 450 },
            style: { background: "linear-gradient(135deg, #ff9a9e 0%, #fad0c4 100%)", color: "#333", width: 240, height: 80, edgeColor: "#ff9a9e" },
            options: [ "The Ministry of Defense remains in Tel Aviv for security reasons.", "For security purposes, the Defense Ministry was kept in Tel Aviv.", "The Defense Ministry stayed in Tel Aviv due to security concerns.", "It was decided to keep the Ministry of Defense in Tel Aviv for security." ],
            correctAnswer: "The Ministry of Defense remains in Tel Aviv for security reasons.",
        },
    ],
    storyConnections: [
      { from: 1, to: 0, relationship: "triggers", color: "#c3cfe2" },
      { from: 0, to: 2, relationship: "leads to", color: "#a1c4fd" },
      { from: 2, to: 3, relationship: "except for", color: "#d299c2" },
      { from: 2, to: 4, relationship: "except for", color: "#d299c2" },
    ],
    tags: ["Legal", "Institutional"],
    actors: ["Israel Governmental"],
    locations: ["Jerusalem"],
    related_places: [],
    dateOptions: [ "23 January 1950 - 13 July 1953", "13 December 1949 - 23 January 1950", "23 January 1951 - 13 July 1952", "13 July 1953 - 1 January 1954" ],
    locationOptions: [ "Jerusalem", "Tel Aviv", "Haifa", "Hebron" ],
    outcomeOptions: [ "Israel establishes Jerusalem as its capital by moving its government institutions there.", "The UN reverses its resolution and recognizes Jerusalem as the capital.", "A permanent international regime is established for the city.", "Government ministries are divided equally between Tel Aviv and Jerusalem." ],
  },
  {
    title: "Absentee Property Law, 5710-1950",
    date: "14 March 1950",
    location: "Israel",
    outcome: "A legal framework is created for the state to take control of Palestinian refugee property.",
    storyElements: [
        {
            text: "The law seeks to 'legalize' the confiscation of property left by Palestinian refugees.",
            category: "goal",
            position: { x: 100, y: 150 },
            style: { background: "linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)", color: "#333", width: 250, height: 100, edgeColor: "#c3cfe2" },
            options: [ "The law seeks to 'legalize' the confiscation of property left by Palestinian refugees.", "The legislation aims to provide a legal basis for seizing refugee property.", "The purpose of the law is to legitimize the takeover of property from refugees.", "The state creates a law to formally justify the seizure of refugee assets." ],
            correctAnswer: "The law seeks to 'legalize' the confiscation of property left by Palestinian refugees.",
        },
        {
            text: "It defines an 'absentee' as any Arab who left his residence during the war.",
            category: "definition",
            position: { x: 400, y: 300 },
            style: { background: "linear-gradient(135deg, #a1c4fd 0%, #c2e9fb 100%)", color: "#333", width: 260, height: 90, edgeColor: "#a1c4fd" },
            options: [ "It defines an 'absentee' as any Arab who left his residence during the war.", "The law's definition of 'absentee' includes any Arab who departed their home in the war.", "An 'absentee' is defined as any Arab person who left their place of living during the conflict.", "Under the law, an Arab who left their home during the war is classified as an 'absentee'." ],
            correctAnswer: "It defines an 'absentee' as any Arab who left his residence during the war.",
        },
        {
            text: "Absentees’ property is automatically transferred to the 'Custodian of Absentee Property.'",
            category: "mechanism",
            position: { x: 700, y: 150 },
            style: { background: "linear-gradient(135deg, #d299c2 0%, #fef9d7 100%)", color: "#333", width: 250, height: 100, edgeColor: "#d299c2" },
            options: [ "Absentees’ property is automatically transferred to the 'Custodian of Absentee Property.'", "Property of absentees is moved by default to the control of the 'Custodian of Absentee Property.'", "The 'Custodian of Absentee Property' takes automatic control of the property of absentees.", "An automatic transfer of absentee property to the 'Custodian of Absentee Property' occurs." ],
            correctAnswer: "Absentees’ property is automatically transferred to the 'Custodian of Absentee Property.'",
        },
        {
            text: "The Custodian can then sell the property to the 'Development Authority.'",
            category: "consequence",
            position: { x: 650, y: 450 },
            style: { background: "linear-gradient(135deg, #ff9a9e 0%, #fad0c4 100%)", color: "#333", width: 240, height: 90, edgeColor: "#ff9a9e" },
            options: [ "The Custodian can then sell the property to the 'Development Authority.'", "The 'Development Authority' is allowed to purchase the property from the Custodian.", "The Custodian is authorized to sell the assets to the 'Development Authority.'", "It is permitted for the property to be sold by the Custodian to the 'Development Authority.'" ],
            correctAnswer: "The Custodian can then sell the property to the 'Development Authority.'",
        },
    ],
    storyConnections: [
      { from: 0, to: 1, relationship: "requires a", color: "#c3cfe2" },
      { from: 1, to: 2, relationship: "triggers", color: "#a1c4fd" },
      { from: 2, to: 3, relationship: "enables", color: "#d299c2" },
    ],
    tags: ["Legal", "Colonization"],
    actors: ["Israel Governmental"],
    locations: ["Israel"],
    related_places: [],
    dateOptions: [ "14 March 1950", "14 December 1948", "14 March 1949", "14 May 1950" ],
    locationOptions: [ "Israel", "The West Bank", "Jerusalem", "Gaza Strip" ],
    outcomeOptions: [ "A legal framework is created for the state to take control of Palestinian refugee property.", "A system is established for the state to manage assets of Palestinian refugees.", "The state gains a legal method for acquiring the property of refugees.", "A law is passed that allows the government to seize refugee property." ],
  },
  {
    title: "Special International Regime for Jerusalem",
    date: "4 April 1950",
    location: "Jerusalem",
    outcome: "A statute is approved to make Jerusalem an international city under UN administration.",
    storyElements: [
        {
            text: "The UN Trusteeship Council approves a Statute for Jerusalem.",
            category: "action",
            position: { x: 400, y: 150 },
            style: { background: "linear-gradient(135deg, #a1c4fd 0%, #c2e9fb 100%)", color: "#333", width: 260, height: 90, edgeColor: "#a1c4fd" },
            options: [ "The UN Trusteeship Council approves a Statute for Jerusalem.", "A Statute for Jerusalem is approved by the UN Trusteeship Council.", "The UN Trusteeship Council endorses a specific Statute for Jerusalem.", "Approval is given by the UN Trusteeship Council for a Jerusalem Statute." ],
            correctAnswer: "The UN Trusteeship Council approves a Statute for Jerusalem.",
        },
        {
            text: "The statute provides for a Special International Regime for the city.",
            category: "provision",
            position: { x: 150, y: 300 },
            style: { background: "linear-gradient(135deg, #d299c2 0%, #fef9d7 100%)", color: "#333", width: 250, height: 90, edgeColor: "#d299c2" },
            options: [ "The statute provides for a Special International Regime for the city.", "A Special International Regime for the city is established by the statute.", "The statute's text outlines a Special International Regime for the city.", "Provision is made in the statute for a Special International Regime for the city." ],
            correctAnswer: "The statute provides for a Special International Regime for the city.",
        },
        {
            text: "It constitutes the city as a corpus separatum under UN administration.",
            category: "status",
            position: { x: 650, y: 300 },
            style: { background: "linear-gradient(135deg, #ff9a9e 0%, #fad0c4 100%)", color: "#333", width: 250, height: 90, edgeColor: "#ff9a9e" },
            options: [ "It constitutes the city as a corpus separatum under UN administration.", "The city is made a corpus separatum to be administered by the UN.", "It establishes Jerusalem as a corpus separatum under the UN's administration.", "Under the statute, the city becomes a corpus separatum managed by the UN." ],
            correctAnswer: "It constitutes the city as a corpus separatum under UN administration.",
        },
    ],
    storyConnections: [
      { from: 0, to: 1, relationship: "which provides for a", color: "#a1c4fd" },
      { from: 0, to: 2, relationship: "and constitutes it as a", color: "#a1c4fd" },
    ],
    tags: ["Diplomatic", "Policy-Program"],
    actors: ["UN Inter-Governmental"],
    locations: ["Jerusalem"],
    related_places: [],
    dateOptions: [ "4 April 1950", "23 January 1950", "13 December 1949", "4 April 1951" ],
    locationOptions: [ "Jerusalem", "Tel Aviv", "Geneva, Switzerland", "New York, USA" ],
    outcomeOptions: [ "A statute is approved to make Jerusalem an international city under UN administration.", "A plan to create an international zone in Jerusalem is formally approved.", "The UN approves a statute for an international administration of Jerusalem.", "A formal statute is passed to put Jerusalem under a UN-managed international regime." ],
  },
  {
    title: "Jordanian Parliamentary Elections; Formal Unification of the Two Banks",
    date: "11 April 1950 - 24 April 1950",
    location: "Jordan, West Bank",
    outcome: "The East and West Banks are formally unified into the Hashemite Kingdom of Jordan.",
    storyElements: [
        {
            text: "Parliamentary elections are held with 20 representatives from the East Bank and 20 from the West Bank.",
            category: "action",
            position: { x: 100, y: 150 },
            style: { background: "linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)", color: "#333", width: 250, height: 110, edgeColor: "#c3cfe2" },
            options: [ "Parliamentary elections are held with 20 representatives from the East Bank and 20 from the West Bank.", "Elections for parliament take place, with 20 deputies elected from each of the two banks.", "The country holds parliamentary elections, choosing 20 representatives from both East and West Banks.", "With 20 members elected from each bank, parliamentary elections are conducted." ],
            correctAnswer: "Parliamentary elections are held with 20 representatives from the East Bank and 20 from the West Bank.",
        },
        {
            text: "The new National Assembly (Senate and Chamber of Deputies) confirms the unification of the two banks.",
            category: "resolution",
            position: { x: 400, y: 300 },
            style: { background: "linear-gradient(135deg, #a1c4fd 0%, #c2e9fb 100%)", color: "#333", width: 260, height: 110, edgeColor: "#a1c4fd" },
            options: [ "The new National Assembly (Senate and Chamber of Deputies) confirms the unification of the two banks.", "The unification of the banks is confirmed by the new National Assembly's two houses.", "Confirmation of the unification of the two banks comes from the new National Assembly.", "The two houses of the new National Assembly ratify the unification of the banks." ],
            correctAnswer: "The new National Assembly (Senate and Chamber of Deputies) confirms the unification of the two banks.",
        },
        {
            text: "This confirmation creates a single state: the Hashemite Kingdom of Jordan.",
            category: "outcome",
            position: { x: 700, y: 150 },
            style: { background: "linear-gradient(135deg, #d299c2 0%, #fef9d7 100%)", color: "#333", width: 250, height: 90, edgeColor: "#d299c2" },
            options: [ "This confirmation creates a single state: the Hashemite Kingdom of Jordan.", "A single state, the Hashemite Kingdom of Jordan, is formed by this confirmation.", "The result of this confirmation is one state called the Hashemite Kingdom of Jordan.", "The Hashemite Kingdom of Jordan is established as a single state following the confirmation." ],
            correctAnswer: "This confirmation creates a single state: the Hashemite Kingdom of Jordan.",
        },
        {
            text: "A Royal Assent promulgates the Act of the National Assembly on the same day.",
            category: "legalization",
            position: { x: 650, y: 450 },
            style: { background: "linear-gradient(135deg, #ff9a9e 0%, #fad0c4 100%)", color: "#333", width: 240, height: 90, edgeColor: "#ff9a9e" },
            options: [ "A Royal Assent promulgates the Act of the National Assembly on the same day.", "The National Assembly's Act is put into law by a Royal Assent that day.", "On the same day, the Act of the National Assembly is enacted via Royal Assent.", "The law is made official through a Royal Assent on the same day." ],
            correctAnswer: "A Royal Assent promulgates the Act of the National Assembly on the same day.",
        },
    ],
    storyConnections: [
      { from: 0, to: 1, relationship: "elects", color: "#c3cfe2" },
      { from: 1, to: 2, relationship: "which creates", color: "#a1c4fd" },
      { from: 1, to: 3, relationship: "is legalized by", color: "#a1c4fd" },
    ],
    tags: ["Institutional", "Legal"],
    actors: ["Jordan Governmental", "Palestine Quasi-Governmental"],
    locations: ["Jordan", "West Bank"],
    related_places: [],
    dateOptions: [ "11 April 1950 - 24 April 1950", "13 December 1949 - 11 April 1950", "24 April 1950 - 1 May 1950", "11 April 1949 - 24 April 1949" ],
    locationOptions: [ "Jordan, West Bank", "Amman, Jordan", "Jerusalem", "East Bank only" ],
    outcomeOptions: [ "The East and West Banks are formally unified into the Hashemite Kingdom of Jordan.", "Formal unification of the two banks into one kingdom, the Hashemite Kingdom of Jordan, occurs.", "A single state, the Hashemite Kingdom of Jordan, is formed by formally unifying the two banks.", "The Hashemite Kingdom of Jordan is created through the official unification of the East and West Banks." ],
  },
  {
    title: "Great Britain Announces Formal Recognition of Extended Kingdom of Jordan and de jure Recognition of Israel Simultaneously",
    date: "27 April 1950",
    location: "Great Britain",
    outcome: "Britain recognizes both the expanded Kingdom of Jordan and the State of Israel, but withholds recognition of sovereignty over Jerusalem.",
    storyElements: [
        {
            text: "Great Britain accords formal recognition to the union of Jordan and the West Bank.",
            category: "action",
            position: { x: 100, y: 150 },
            style: { background: "linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)", color: "#333", width: 250, height: 100, edgeColor: "#c3cfe2" },
            options: [ "Great Britain accords formal recognition to the union of Jordan and the West Bank.", "Formal recognition is given by Great Britain to the Jordan-West Bank union.", "The union of Jordan and the West Bank is formally recognized by Great Britain.", "Great Britain officially recognizes the unification of Jordan and the West Bank." ],
            correctAnswer: "Great Britain accords formal recognition to the union of Jordan and the West Bank.",
        },
        {
            text: "The Anglo-Jordan Treaty of Alliance is made applicable to all territory in the union.",
            category: "consequence",
            position: { x: 400, y: 300 },
            style: { background: "linear-gradient(135deg, #a1c4fd 0%, #c2e9fb 100%)", color: "#333", width: 260, height: 100, edgeColor: "#a1c4fd" },
            options: [ "The Anglo-Jordan Treaty of Alliance is made applicable to all territory in the union.", "Provisions of the Anglo-Jordan Treaty now apply to the entire unified territory.", "The alliance treaty with Jordan is extended to cover all land in the union.", "Applicability of the Anglo-Jordan Treaty is extended to the whole union." ],
            correctAnswer: "The Anglo-Jordan Treaty of Alliance is made applicable to all territory in the union.",
        },
        {
            text: "Simultaneously, Great Britain accords de jure recognition to the State of Israel.",
            category: "action",
            position: { x: 700, y: 150 },
            style: { background: "linear-gradient(135deg, #d299c2 0%, #fef9d7 100%)", color: "#333", width: 250, height: 100, edgeColor: "#d299c2" },
            options: [ "Simultaneously, Great Britain accords de jure recognition to the State of Israel.", "De jure recognition is granted to Israel by Great Britain at the same time.", "At the same moment, Israel receives de jure recognition from Great Britain.", "Great Britain gives de jure recognition to the State of Israel concurrently." ],
            correctAnswer: "Simultaneously, Great Britain accords de jure recognition to the State of Israel.",
        },
        {
            text: "Britain withholds recognition of sovereignty over Jerusalem, only allowing de facto control.",
            category: "exception",
            position: { x: 400, y: 450 },
            style: { background: "linear-gradient(135deg, #ff9a9e 0%, #fad0c4 100%)", color: "#333", width: 260, height: 100, edgeColor: "#ff9a9e" },
            options: [ "Britain withholds recognition of sovereignty over Jerusalem, only allowing de facto control.", "Sovereignty over Jerusalem is not recognized by Britain, merely de facto control.", "Britain only recognizes de facto control over Jerusalem, not full sovereignty.", "Recognition of sovereignty over Jerusalem is withheld by Britain, allowing only for de facto status." ],
            correctAnswer: "Britain withholds recognition of sovereignty over Jerusalem, only allowing de facto control.",
        },
    ],
    storyConnections: [
      { from: 0, to: 1, relationship: "which extends the", color: "#c3cfe2" },
      { from: 0, to: 3, relationship: "but with an", color: "#c3cfe2" },
      { from: 2, to: 3, relationship: "but with an", color: "#d299c2" },
    ],
    tags: ["Diplomatic"],
    actors: ["Israel Governmental", "Great Britain Governmental"],
    locations: ["Great Britain"],
    related_places: [],
    dateOptions: [ "27 April 1950", "24 April 1950", "15 March 1948", "27 April 1949" ],
    locationOptions: [ "Great Britain", "Jerusalem", "Jordan", "Israel" ],
    outcomeOptions: [ "Britain recognizes both the expanded Kingdom of Jordan and the State of Israel, but withholds recognition of sovereignty over Jerusalem.", "Both the union of Jordan and the state of Israel are recognized by Britain, with an exception for Jerusalem's sovereignty.", "Britain acknowledges the expanded Jordanian kingdom and Israel, while not recognizing sovereignty over Jerusalem.", "Recognition is granted to Jordan's union and Israel, though Britain withholds recognition of sovereignty for Jerusalem." ],
  },
  {
    title: "Elections at al-Urwa al-Wuthqa Society",
    date: "May 1950",
    location: "Lebanon",
    outcome: "The Arab Nationalists' list wins all seats, solidifying their influence in the student society.",
    storyElements: [
        {
            text: "Al-Urwa al-Wuthqa Society, a student group at AUB, holds its annual elections.",
            category: "action",
            position: { x: 100, y: 150 },
            style: { background: "linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)", color: "#333", width: 250, height: 100, edgeColor: "#c3cfe2" },
            options: [ "Al-Urwa al-Wuthqa Society, a student group at AUB, holds its annual elections.", "The annual elections of the al-Urwa al-Wuthqa Society, a student association at AUB, take place.", "A student society at AUB, al-Urwa al-Wuthqa, conducts its yearly elections.", "The holding of annual elections occurs at AUB's al-Urwa al-Wuthqa student society." ],
            correctAnswer: "Al-Urwa al-Wuthqa Society, a student group at AUB, holds its annual elections.",
        },
        {
            text: "The Arab Nationalists' list wins all eight seats, with George Habash elected president.",
            category: "outcome",
            position: { x: 400, y: 300 },
            style: { background: "linear-gradient(135deg, #a1c4fd 0%, #c2e9fb 100%)", color: "#333", width: 260, height: 100, edgeColor: "#a1c4fd" },
            options: [ "The Arab Nationalists' list wins all eight seats, with George Habash elected president.", "All eight seats are won by the Arab Nationalists' list, and George Habash becomes president.", "George Habash is elected president as the Arab Nationalists' list secures all eight seats.", "A clean sweep of all eight seats is achieved by the Arab Nationalists' list, making George Habash president." ],
            correctAnswer: "The Arab Nationalists' list wins all eight seats, with George Habash elected president.",
        },
        {
            text: "Many members are inspired by their faculty advisor, Constantine Zurayk.",
            category: "influence",
            position: { x: 700, y: 150 },
            style: { background: "linear-gradient(135deg, #d299c2 0%, #fef9d7 100%)", color: "#333", width: 250, height: 90, edgeColor: "#d299c2" },
            options: [ "Many members are inspired by their faculty advisor, Constantine Zurayk.", "Constantine Zurayk, the faculty advisor, serves as an inspiration for many members.", "The society's faculty advisor, Constantine Zurayk, inspires many of the members.", "Inspiration for many members comes from their faculty advisor, Constantine Zurayk." ],
            correctAnswer: "Many members are inspired by their faculty advisor, Constantine Zurayk.",
        },
        {
            text: "Zurayk promotes Arab nationalism, unity, and rationalism as necessary for the struggle.",
            category: "ideology",
            position: { x: 650, y: 450 },
            style: { background: "linear-gradient(135deg, #ff9a9e 0%, #fad0c4 100%)", color: "#333", width: 260, height: 100, edgeColor: "#ff9a9e" },
            options: [ "Zurayk promotes Arab nationalism, unity, and rationalism as necessary for the struggle.", "Arab nationalism, unity, and rationalism are promoted by Zurayk as essential for the struggle.", "The promotion of Arab nationalism, unity, and rationalism as needed for the struggle is done by Zurayk.", "The struggle requires Arab nationalism, unity, and rationalism, according to Zurayk's promotion." ],
            correctAnswer: "Zurayk promotes Arab nationalism, unity, and rationalism as necessary for the struggle.",
        },
    ],
    storyConnections: [
      { from: 0, to: 1, relationship: "results in", color: "#c3cfe2" },
      { from: 2, to: 1, relationship: "inspires", color: "#d299c2" },
      { from: 2, to: 3, relationship: "whose ideas promote", color: "#d299c2" },
    ],
    tags: ["Institutional", "Popular action"],
    actors: ["Arabs Non-Governmental", "Palestine Non-Governmental"],
    locations: ["Lebanon"],
    related_places: [],
    dateOptions: [ "May 1950", "August 1948", "May 1949", "January 1950" ],
    locationOptions: [ "Lebanon", "Syria", "Jordan", "Egypt" ],
    outcomeOptions: [ "The Arab Nationalists' list wins all seats, solidifying their influence in the student society.", "A victory by the Arab Nationalists' list in all seats strengthens their position in the society.", "The society's leadership is fully taken by the Arab Nationalists' list after winning the election.", "Winning every seat, the Arab Nationalists' list cements its control over the student society." ],
  },
  {
    title: "Expulsion from Hebron Area",
    date: "3 May 1950",
    location: "Hebron, West Bank",
    outcome: "12,000 Palestinians are expelled by Israeli forces from two villages in the Hebron area.",
    storyElements: [
        {
            text: "Israeli forces drive 12,000 Palestinians from 2 villages in the Hebron area.",
            category: "action",
            position: { x: 400, y: 150 },
            style: { background: "linear-gradient(135deg, #ff9a9e 0%, #fad0c4 100%)", color: "#333", width: 250, height: 100, edgeColor: "#ff9a9e" },
            options: [ "Israeli forces drive 12,000 Palestinians from 2 villages in the Hebron area.", "12,000 Palestinians are driven out of 2 villages near Hebron by Israeli forces.", "The expulsion of 12,000 Palestinians from 2 Hebron-area villages is conducted by Israeli forces.", "From 2 villages in the Hebron region, Israeli forces expel 12,000 Palestinians." ],
            correctAnswer: "Israeli forces drive 12,000 Palestinians from 2 villages in the Hebron area.",
        },
        {
            text: "The expulsion included thousands of dunams of land ready to be harvested.",
            category: "consequence",
            position: { x: 400, y: 350 },
            style: { background: "linear-gradient(135deg, #a1c4fd 0%, #c2e9fb 100%)", color: "#333", width: 260, height: 90, edgeColor: "#a1c4fd" },
            options: [ "The expulsion included thousands of dunams of land ready to be harvested.", "Thousands of dunams of land, prepared for harvesting, were part of the affected area.", "The land from which people were expelled contained thousands of harvest-ready dunams.", "The area affected by the expulsion had thousands of dunams of land ready for harvest." ],
            correctAnswer: "The expulsion included thousands of dunams of land ready to be harvested.",
        },
    ],
    storyConnections: [
      { from: 0, to: 1, relationship: "affecting", color: "#ff9a9e" },
    ],
    tags: ["Violence"],
    actors: ["Israel Governmental", "Palestine Non-Governmental"],
    locations: ["Jordan", "West Bank"],
    related_places: [{ "type": "Place", "name": "Hebron" }],
    dateOptions: [ "3 May 1950", "27 April 1950", "3 June 1950", "3 May 1951" ],
    locationOptions: [ "Hebron, West Bank", "Jerusalem", "Gaza Strip", "Nablus, West Bank" ],
    outcomeOptions: [ "12,000 Palestinians are expelled by Israeli forces from two villages in the Hebron area.", "Israeli forces drive out 12,000 Palestinians from a pair of villages near Hebron.", "The expulsion of 12,000 Palestinians from two Hebron villages by Israeli forces occurs.", "Two villages in the Hebron area see 12,000 Palestinians expelled by Israeli forces." ],
  },
  {
    title: "Tripartite Declaration",
    date: "25 May 1950",
    location: "Great Britain",
    outcome: "The US, UK, and France jointly guarantee the regional status quo and commit to limiting arms sales.",
    storyElements: [
        {
            text: "The US, Britain, and France jointly issue the Tripartite Declaration.",
            category: "action",
            position: { x: 400, y: 150 },
            style: { background: "linear-gradient(135deg, #a1c4fd 0%, #c2e9fb 100%)", color: "#333", width: 260, height: 90, edgeColor: "#a1c4fd" },
            options: [ "The US, Britain, and France jointly issue the Tripartite Declaration.", "A joint declaration is issued by the US, Britain, and France.", "The Tripartite Declaration is issued jointly by the US, Britain, and France.", "France, Britain, and the US collaborate to issue a joint declaration." ],
            correctAnswer: "The US, Britain, and France jointly issue the Tripartite Declaration.",
        },
        {
            text: "It guarantees the territorial status quo from the armistice agreements.",
            category: "provision",
            position: { x: 150, y: 300 },
            style: { background: "linear-gradient(135deg, #d299c2 0%, #fef9d7 100%)", color: "#333", width: 250, height: 100, edgeColor: "#d299c2" },
            options: [ "It guarantees the territorial status quo from the armistice agreements.", "The territorial status quo determined by the armistice is guaranteed.", "A guarantee is made for the territorial status quo established in the armistice.", "The declaration assures the territorial status quo of the armistice deals." ],
            correctAnswer: "It guarantees the territorial status quo from the armistice agreements.",
        },
        {
            text: "It undertakes to limit an Arab-Israeli arms race.",
            category: "provision",
            position: { x: 650, y: 300 },
            style: { background: "linear-gradient(135deg, #ff9a9e 0%, #fad0c4 100%)", color: "#333", width: 250, height: 90, edgeColor: "#ff9a9e" },
            options: [ "It undertakes to limit an Arab-Israeli arms race.", "A commitment is made to limit the arms race between Arabs and Israelis.", "The declaration includes an undertaking to curtail an Arab-Israeli arms race.", "It makes a pledge to restrict the buildup of arms between Arabs and Israelis." ],
            correctAnswer: "It undertakes to limit an Arab-Israeli arms race.",
        },
        {
            text: "The declaration is intended to convince Arabs and Israelis to focus on the Soviet threat.",
            category: "motive",
            position: { x: 400, y: 450 },
            style: { background: "linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)", color: "#333", width: 260, height: 100, edgeColor: "#c3cfe2" },
            options: [ "The declaration is intended to convince Arabs and Israelis to focus on the Soviet threat.", "The purpose of the declaration is to make Arabs and Israelis concentrate on the Soviet threat.", "It is meant to persuade Arabs and Israelis to direct their attention to the Soviet threat.", "The goal is to convince Arabs and Israelis to see the Soviet threat as the main issue." ],
            correctAnswer: "The declaration is intended to convince Arabs and Israelis to focus on the Soviet threat.",
        },
    ],
    storyConnections: [
      { from: 0, to: 1, relationship: "which guarantees", color: "#a1c4fd" },
      { from: 0, to: 2, relationship: "and undertakes to", color: "#a1c4fd" },
      { from: 0, to: 3, relationship: "and intends to", color: "#a1c4fd" },
    ],
    tags: ["Diplomatic", "Policy-Program"],
    actors: ["USA Governmental", "Great Britain Governmental", "France Governmental"],
    locations: ["Great Britain"],
    related_places: [],
    dateOptions: [ "25 May 1950", "27 April 1950", "25 June 1950", "25 May 1951" ],
    locationOptions: [ "Great Britain", "Washington D.C., USA", "Paris, France", "Jerusalem" ],
    outcomeOptions: [ "The US, UK, and France jointly guarantee the regional status quo and commit to limiting arms sales.", "A joint guarantee of the status quo and a pledge to limit arms sales is made by the three powers.", "The three Western powers guarantee the status quo and agree to restrict the regional arms race.", "A commitment to guarantee the status quo and limit arms sales is issued by the US, UK, and France." ],
  },
]